site_name: Documentación DAW
site_description: "Documentación de las prácticas"
site_author: "Álvaro Mejías Benavente"
nav: 
  - Practica 2: Practicas/practica2/docs/index.md
  - Practica 2.2: Practicas/practica2.2/docs/index.md
  - Practica 2.3: Practicas/practica2.3/docs/index.md
  - Practica 2.4: Practicas/practica2.4/docs/index.md
  - Practica 2.5: Practicas/practica2.5/docs/index.md
  - Practica 3.2: Practicas/practica3.2/docs/index.md
  - Practica 4.1: Practicas/practica4.1/docs/index.md
  - Practica 5.1 (Ejercicios Git y Github 1): Practicas/practica5.1/docs/index.md
  - Practica 6.1: Practicas/practica6.1/docs/index.md
  - Practica 6.2: Practicas/practica6.2/docs/index.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: True
theme:
  name: material
  features:
  - toc.integrate
  - header.autohide
  - announce.dismiss
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Cambiar a modo oscuro
      primary: teal
      accent: light green
    - scheme: slate
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo claro
      primary: teal
      accent: light green
  font:
    text: "Verdana"
    code: "Roboto Mono"